<a href="https://colab.research.google.com/github/sgl13/PythonLearning/blob/main/Day12_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to pandas**

Pandas is a fast, powerful, and flexible open-source data manipulation and analysis library built for Python. It provides high-performance data structures designed to make working with structured (tabular, matrix, or time-series) data intuitive and efficient

Series: A 1D labeled array capable of holding any data type (integers, strings, floating-point numbers, Python objects, etc.).

DataFrame: A 2D labeled data structure with columns of potentially different types (similar to a spreadsheet or SQL table).

In [4]:
# NumPy and pandas are typically imported together.
# np and pd are conventional aliases.
import numpy as np
import pandas as pd

In [7]:
# Read in data from a .csv file.
dataframe = pd.read_csv('/content/Telco_customer_churn.csv')

# Print the first 25 rows.
dataframe.head(25)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Premium Tech Support,Unlimited Data,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Score.1,Churn Category
0,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,Yes,0.00,0,20.94,129.09,1,Churned,86,Competitor
1,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,Yes,0.00,0,18.24,169.89,2,Churned,67,Other
2,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,97.20,917.70,3,Churned,86,Other
3,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,0.00,0,136.92,3182.97,3,Churned,84,Other
4,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,2172.17,7208.47,1,Churned,89,Competitor
5,4190-MFLUW,Female,0,Yes,Yes,10,Yes,No,DSL,No,...,Yes,Yes,0.00,0,94.10,622.45,1,Churned,78,Competitor
6,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,No,No,0.00,20,0.00,59.65,3,Churned,91,Competitor
7,1066-JKSGK,Male,0,No,No,1,Yes,No,No,No internet service,...,No,No,0.00,0,33.58,53.73,1,Churned,92,Competitor
8,6467-CHFZW,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,1473.45,6222.60,1,Churned,77,Competitor
9,8665-UTDHZ,Male,0,Yes,Yes,1,No,No phone service,DSL,No,...,No,Yes,0.00,0,0.00,30.20,1,Churned,90,Competitor
10,8773-HHUOZ,Female,0,No,Yes,17,Yes,No,DSL,No,...,No,Yes,0.00,0,689.35,1782.45,1,Churned,74,Competitor
11,6047-YHPVI,Male,0,No,No,5,Yes,No,Fiber optic,No,...,No,Yes,0.00,0,63.00,379.90,1,Churned,66,Competitor
12,5380-WJKOV,Male,0,No,No,34,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,737.46,4286.71,2,Churned,65,Competitor
13,8168-UQWWF,Female,0,No,No,11,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,303.27,1408.67,3,Churned,70,Competitor
14,7760-OYPDY,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,0.00,20,11.70,175.85,1,Churned,90,Competitor
15,9420-LOJKX,Female,0,No,No,15,Yes,No,Fiber optic,Yes,...,No,Yes,0.00,0,59.40,1485.80,1,Churned,82,Competitor
16,7495-OOKFY,Female,1,Yes,No,8,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,390.80,1024.10,3,Churned,69,Competitor
17,1658-BYGOY,Male,1,No,No,18,Yes,Yes,Fiber optic,No,...,No,Yes,45.61,0,203.94,1910.88,2,Churned,81,Competitor
18,5698-BQJOH,Female,0,No,No,9,Yes,Yes,Fiber optic,No,...,No,Yes,0.00,0,244.89,1102.14,3,Churned,96,Price
19,5919-TMRGD,Female,0,No,Yes,1,Yes,No,Fiber optic,No,...,No,Yes,0.00,0,13.13,92.48,1,Churned,87,Competitor
20,9191-MYQKX,Female,0,Yes,No,7,Yes,No,Fiber optic,No,...,No,Yes,0.00,0,60.83,557.73,1,Churned,70,Dissatisfaction
21,8637-XJIVR,Female,0,No,No,12,Yes,Yes,Fiber optic,Yes,...,No,No,0.00,80,304.08,1311.43,1,Churned,86,Attitude
22,0278-YXOOG,Male,0,No,No,5,Yes,No,No,No internet service,...,No,No,0.00,0,171.30,285.15,3,Churned,66,Attitude
23,4598-XLKNJ,Female,1,Yes,No,25,Yes,No,Fiber optic,No,...,No,Yes,13.43,0,494.00,2995.07,2,Churned,88,Dissatisfaction
24,3192-NQECA,Male,0,Yes,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,0.00,0,1005.72,8617.57,2,Churned,86,Competitor

In [8]:
# Calculate the mean of the Total Revenue column.
dataframe['Total Revenue'].mean()

np.float64(3034.3790558000846)

In [9]:
# Calculate the maximum value contained in the Total Revenue column.
dataframe['Total Revenue'].max()

11979.34

In [12]:
# Calculate the minimum value contained in the Total Revenue column.
dataframe['Total Revenue'].min()

21.36

In [13]:
# Calculate the standard deviation of the values in the Total Revenue column.
dataframe['Total Revenue'].std()

2865.204541511528

In [14]:
# Return the number of rows that share the same value in the Churn Score.1 column.
dataframe['Churn Score.1'].value_counts()

Churn Score.1
91    202
80    150
71    148
77    145
67    142
     ...
88     33
9       3
8       2
7       2
5       1
Name: count, Length: 81, dtype: int64

In [15]:
# The describe() method returns summary statistics of the dataframe.
dataframe.describe()

,SeniorCitizen,tenure,MonthlyCharges,churn_rate,Churn Score,CLTV,Count,Zip Code,Latitude,Longitude,Age,Number of Referrals,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Churn Score.1
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692,0.265370,58.699418,4400.295755,1.0,93521.964646,36.282441,-119.798880,46.509726,1.951867,22.958954,20.515405,1.962182,6.860713,749.099262,3034.379056,3.244924,58.505040
std,0.368612,24.559481,30.090047,0.441561,21.525131,1183.057152,0.0,1865.794555,2.455723,2.157889,16.750352,3.001199,15.448113,20.418940,7.902614,25.104978,846.660055,2865.204542,1.201657,21.170031
min,0.000000,0.000000,18.250000,0.000000,5.000000,2003.000000,1.0,90001.000000,32.555828,-124.301372,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.360000,1.000000,5.000000
25%,0.000000,9.000000,35.500000,0.000000,40.000000,3469.000000,1.0,92102.000000,34.030915,-121.815412,32.000000,0.000000,9.210000,3.000000,0.000000,0.000000,70.545000,605.610000,3.000000,40.000000
50%,0.000000,29.000000,70.350000,0.000000,61.000000,4527.000000,1.0,93552.000000,36.391777,-119.730885,46.000000,0.000000,22.890000,17.000000,0.000000,0.000000,401.440000,2108.640000,3.000000,61.000000
75%,0.000000,55.000000,89.850000,1.000000,75.000000,5380.500000,1.0,95351.000000,38.224869,-118.043237,60.000000,3.000000,36.395000,27.000000,0.000000,0.000000,1191.100000,4801.145000,4.000000,75.500000
max,1.000000,72.000000,118.750000,1.000000,100.000000,6500.000000,1.0,96161.000000,41.962127,-114.192901,80.000000,11.000000,49.990000,85.000000,49.790000,150.000000,3564.720000,11979.340000,5.000000,96.000000

In [16]:
import pandas as pd

# Use pd.DataFrame() function to create a dataframe from a dictionary.
data = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=data)
df

   col1  col2
0     1     3
1     2     4

In [17]:
# Use pd.DataFrame() function to create a dataframe from a NumPy array.
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'], index=['x', 'y', 'z'])
df2

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [20]:
# Instantiate a dictionary of planetary data.
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars',
                   'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
       'radius_km': [2440, 6052, 6371, 3390, 69911, 58232,
                     25362, 24622],
       'moons': [0, 0, 1, 2, 80, 83, 27, 14]
        }
# Use pd.DataFrame() function to convert dictionary to dataframe.
planets = pd.DataFrame(data)
planets

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [21]:
# Create a Boolean mask of planets with fewer than 20 moons.
mask = planets['moons'] < 20
mask

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: moons, dtype: bool

In [23]:
# Apply the Boolean mask to the dataframe to filter it so it contains
# only the planets with fewer than 20 moons.
planets[mask]

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14

In [24]:
# Define the Boolean mask and apply it in a single line.
planets[planets['moons'] < 20]

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14

In [25]:
# Boolean masks don't change the data. They're just views.
planets

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [26]:
# You can assign a dataframe view to a named variable.
moons_under_20 = planets[mask]
moons_under_20

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14

In [27]:
# Create a Boolean mask of planets with fewer than 10 moons OR more than 50 moons.
mask = (planets['moons'] < 10) | (planets['moons'] > 50)
mask

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
Name: moons, dtype: bool

In [28]:
# Apply the Boolean mask to filter the data.
planets[mask]

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83

In [29]:
# Create a Boolean mask of planets with more than 20 moons, excluding them if they
# have 80 moons or if their radius is less than 50,000 km.
mask = (planets['moons'] > 20) & ~(planets['moons'] == 80) & ~(planets['radius_km'] < 50000)

# Apply the mask
planets[mask]

   planet  radius_km  moons
5  Saturn      58232     83

**Grouping and aggregation**

In [30]:
# Instantiate a dictionary of planetary data.
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars',
                   'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [2440, 6052, 6371, 3390, 69911, 58232,
                     25362, 24622],
        'moons': [0, 0, 1, 2, 80, 83, 27, 14],
        'type': ['terrestrial', 'terrestrial', 'terrestrial', 'terrestrial',
                 'gas giant', 'gas giant', 'ice giant', 'ice giant'],
        'rings': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes','yes'],
        'mean_temp_c': [167, 464, 15, -65, -110, -140, -195, -200],
        'magnetic_field': ['yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes']
        }

# Use pd.DataFrame() function to convert dictionary to dataframe.
planets = pd.DataFrame(data)
planets

    planet  radius_km  moons         type rings  mean_temp_c magnetic_field
0  Mercury       2440      0  terrestrial    no          167            yes
1    Venus       6052      0  terrestrial    no          464             no
2    Earth       6371      1  terrestrial    no           15            yes
3     Mars       3390      2  terrestrial    no          -65             no
4  Jupiter      69911     80    gas giant   yes         -110            yes
5   Saturn      58232     83    gas giant   yes         -140            yes
6   Uranus      25362     27    ice giant   yes         -195            yes
7  Neptune      24622     14    ice giant   yes         -200            yes

In [31]:
# The groupby() function returns a groupby object.
planets.groupby(['type'])

In [32]:
# Apply the sum() function to the groupby object to get the sum
# of the values in each numerical column for each group.
planets.groupby(['type']).sum()

,planet,radius_km,moons,rings,mean_temp_c,magnetic_field
type,,,,,,
gas giant,JupiterSaturn,128143,163,yesyes,-250,yesyes
ice giant,UranusNeptune,49984,41,yesyes,-395,yesyes
terrestrial,MercuryVenusEarthMars,18253,3,nononono,581,yesnoyesno

In [33]:
# Apply the sum function to the groupby object and select
# only the 'moons' column.
planets.groupby(['type']).sum()[['moons']]

             moons
type
gas giant      163
ice giant       41
terrestrial      3

In [36]:
# Group by type and magnetic_field and get the mean of the values
# in the numeric columns for each group.
planets.groupby(['type', 'magnetic_field']).mean(numeric_only=True)

                            radius_km  moons  mean_temp_c
type        magnetic_field
gas giant   yes               64071.5   81.5       -125.0
ice giant   yes               24992.0   20.5       -197.5
terrestrial no                 4721.0    1.0        199.5
            yes                4405.5    0.5         91.0

In [43]:
# Group by type, then use the agg() function to get the mean and median
# of the values in the numeric columns for each group.
# Select only numeric columns for aggregation
numeric_planets = planets.select_dtypes(include=np.number)
numeric_planets.groupby(planets['type']).agg(['mean', 'median'])

            radius_km           moons        mean_temp_c
                 mean   median   mean median        mean median
type
gas giant    64071.50  64071.5  81.50   81.5     -125.00 -125.0
ice giant    24992.00  24992.0  20.50   20.5     -197.50 -197.5
terrestrial   4563.25   4721.0   0.75    0.5      145.25   91.0

In [45]:
# Group by type and magnetic_field, then use the agg() function to get the
# mean and max of the values in the numeric columns for each group.
# Select only numeric columns for aggregation
numeric_planets = planets.select_dtypes(include=np.number)
numeric_planets.groupby([planets['type'], planets['magnetic_field']]).agg(['mean', 'max'])

                           radius_km        moons     mean_temp_c
                                mean    max  mean max        mean  max
type        magnetic_field
gas giant   yes              64071.5  69911  81.5  83      -125.0 -110
ice giant   yes              24992.0  25362  20.5  27      -197.5 -195
terrestrial no                4721.0   6052   1.0   2       199.5  464
            yes               4405.5   6371   0.5   1        91.0  167

In [46]:
# Define a function that returns the 90 percentile of an array.
def percentile_90(x):
    return x.quantile(0.9)

In [48]:
# Group by type and magnetic_field, then use the agg() function to apply the
# mean and the custom-defined `percentile_90()` function to the numeric
# columns for each group.
numeric_planets = planets.select_dtypes(include=np.number)
numeric_planets.groupby([planets['type'], planets['magnetic_field']]).agg(['mean', percentile_90])

                           radius_km               moons                \
                                mean percentile_90  mean percentile_90
type        magnetic_field
gas giant   yes              64071.5       68743.1  81.5          82.7
ice giant   yes              24992.0       25288.0  20.5          25.7
terrestrial no                4721.0        5785.8   1.0           1.8
            yes               4405.5        5977.9   0.5           0.9

                           mean_temp_c
                                  mean percentile_90
type        magnetic_field
gas giant   yes                 -125.0        -113.0
ice giant   yes                 -197.5        -195.5
terrestrial no                   199.5         411.1
            yes                   91.0         151.8

**Merging and joining data**

In [49]:
# Instantiate a dictionary of planetary data.
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars'],
        'radius_km': [2440, 6052, 6371, 3390],
        'moons': [0, 0, 1, 2],
        }
# Use pd.DataFrame() function to convert dictionary to dataframe.
df1 = pd.DataFrame(data)
df1

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2

In [50]:
# Instantiate a dictionary of planetary data.
data = {'planet': ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [69911, 58232, 25362, 24622],
        'moons': [80, 83, 27, 14],
        }
# Use pd.DataFrame() function to convert dictionary to dataframe.
df2 = pd.DataFrame(data)
df2

    planet  radius_km  moons
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24622     14

In [51]:
# The pd.concat() function can combine the two dataframes along axis 0,
# with the second dataframe being added as new rows to the first dataframe.
df3 = pd.concat([df1, df2], axis=0)
df3

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24622     14

In [52]:
# Reset the row indices.
df3 = df3.reset_index(drop=True)
df3

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [53]:
data = {'planet': ['Earth', 'Mars','Jupiter', 'Saturn', 'Uranus',
                   'Neptune', 'Janssen', 'Tadmor'],
        'type': ['terrestrial', 'terrestrial','gas giant', 'gas giant',
                 'ice giant', 'ice giant', 'super earth','gas giant'],
        'rings': ['no', 'no', 'yes', 'yes', 'yes','yes', 'no', None],
        'mean_temp_c': [15, -65, -110, -140, -195, -200, None, None],
        'magnetic_field': ['yes', 'no', 'yes', 'yes', 'yes', 'yes', None, None],
        'life': [1, 0, 0, 0, 0, 0, 1, 1]
        }
df4 = pd.DataFrame(data)

In [54]:
df4

    planet         type rings  mean_temp_c magnetic_field  life
0    Earth  terrestrial    no         15.0            yes     1
1     Mars  terrestrial    no        -65.0             no     0
2  Jupiter    gas giant   yes       -110.0            yes     0
3   Saturn    gas giant   yes       -140.0            yes     0
4   Uranus    ice giant   yes       -195.0            yes     0
5  Neptune    ice giant   yes       -200.0            yes     0
6  Janssen  super earth    no          NaN           None     1
7   Tadmor    gas giant  None          NaN           None     1

In [55]:
# Use pd.merge() to combine dataframes.
# Inner merge retains only keys that appear in both dataframes.
inner = pd.merge(df3, df4, on='planet', how='inner')
inner

,planet,radius_km,moons,type,rings,mean_temp_c,magnetic_field,life
0,Earth,6371,1,terrestrial,no,15.0,yes,1
1,Mars,3390,2,terrestrial,no,-65.0,no,0
2,Jupiter,69911,80,gas giant,yes,-110.0,yes,0
3,Saturn,58232,83,gas giant,yes,-140.0,yes,0
4,Uranus,25362,27,ice giant,yes,-195.0,yes,0
5,Neptune,24622,14,ice giant,yes,-200.0,yes,0

In [56]:
# Use pd.merge() to combine dataframes.
# Outer merge retains all keys from both dataframes.
outer = pd.merge(df3, df4, on='planet', how='outer')
outer

,planet,radius_km,moons,type,rings,mean_temp_c,magnetic_field,life
0,Earth,6371.0,1.0,terrestrial,no,15.0,yes,1.0
1,Janssen,NaN,NaN,super earth,no,NaN,None,1.0
2,Jupiter,69911.0,80.0,gas giant,yes,-110.0,yes,0.0
3,Mars,3390.0,2.0,terrestrial,no,-65.0,no,0.0
4,Mercury,2440.0,0.0,NaN,NaN,NaN,NaN,NaN
5,Neptune,24622.0,14.0,ice giant,yes,-200.0,yes,0.0
6,Saturn,58232.0,83.0,gas giant,yes,-140.0,yes,0.0
7,Tadmor,NaN,NaN,gas giant,None,NaN,None,1.0
8,Uranus,25362.0,27.0,ice giant,yes,-195.0,yes,0.0
9,Venus,6052.0,0.0,NaN,NaN,NaN,NaN,NaN

In [57]:
# Use pd.merge() to combine dataframes.
# Left merge retains only keys that appear in the left dataframe.
left = pd.merge(df3, df4, on='planet', how='left')
left

,planet,radius_km,moons,type,rings,mean_temp_c,magnetic_field,life
0,Mercury,2440,0,NaN,NaN,NaN,NaN,NaN
1,Venus,6052,0,NaN,NaN,NaN,NaN,NaN
2,Earth,6371,1,terrestrial,no,15.0,yes,1.0
3,Mars,3390,2,terrestrial,no,-65.0,no,0.0
4,Jupiter,69911,80,gas giant,yes,-110.0,yes,0.0
5,Saturn,58232,83,gas giant,yes,-140.0,yes,0.0
6,Uranus,25362,27,ice giant,yes,-195.0,yes,0.0
7,Neptune,24622,14,ice giant,yes,-200.0,yes,0.0

In [58]:
# Use pd.merge() to combine dataframes.
# Right merge retains only keys that appear in right dataframe.
right = pd.merge(df3, df4, on='planet', how='right')
right

,planet,radius_km,moons,type,rings,mean_temp_c,magnetic_field,life
0,Earth,6371.0,1.0,terrestrial,no,15.0,yes,1
1,Mars,3390.0,2.0,terrestrial,no,-65.0,no,0
2,Jupiter,69911.0,80.0,gas giant,yes,-110.0,yes,0
3,Saturn,58232.0,83.0,gas giant,yes,-140.0,yes,0
4,Uranus,25362.0,27.0,ice giant,yes,-195.0,yes,0
5,Neptune,24622.0,14.0,ice giant,yes,-200.0,yes,0
6,Janssen,NaN,NaN,super earth,no,NaN,None,1
7,Tadmor,NaN,NaN,gas giant,None,NaN,None,1

In [59]:
#accessing data from dataframe
data=[
 {'name':'shivu','age':23,'city':'banglore'},
 {'name':'john','age':26,'city':'banglore'},
 {'name':'darsh','age':28,'city':'banglore'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age      city
0  shivu   23  banglore
1   john   26  banglore
2  darsh   28  banglore
<class 'pandas.core.frame.DataFrame'>

In [60]:
df

    name  age      city
0  shivu   23  banglore
1   john   26  banglore
2  darsh   28  banglore

In [61]:
df['name'] #work with column

0    shivu
1     john
2    darsh
Name: name, dtype: object

In [62]:
df.loc[0][2] # only row index

/tmp/ipykernel_733/1802983810.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][2] # only row index

'banglore'

In [63]:
df.iloc[0][1] #index specific location

/tmp/ipykernel_733/3891654219.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1] #index specific location

np.int64(23)

In [64]:
#accessing specified element
df['name']

0    shivu
1     john
2    darsh
Name: name, dtype: object

In [65]:
df

    name  age      city
0  shivu   23  banglore
1   john   26  banglore
2  darsh   28  banglore

In [66]:
df.at[2,'age']

np.int64(28)

In [67]:
df.at[2,'name']

'darsh'

In [68]:
#access specified element using iat
df.iat[2,2]

'banglore'

In [69]:
##data manipulation with dataframe
df

    name  age      city
0  shivu   23  banglore
1   john   26  banglore
2  darsh   28  banglore

In [70]:
##adding a column
df['salary'] = [50000,60000,70000]
df

    name  age      city  salary
0  shivu   23  banglore   50000
1   john   26  banglore   60000
2  darsh   28  banglore   70000

In [71]:
##remove column
df.drop('salary',axis=1) #axis = 0 mean  axis have 2 values 1 row value first it check row index not go with column because default axis=0 but it error change value to 1

    name  age      city
0  shivu   23  banglore
1   john   26  banglore
2  darsh   28  banglore

In [72]:
df #it again show salary because axis=1 is temprovary not permanent so we give inplace=True it drop permanently

    name  age      city  salary
0  shivu   23  banglore   50000
1   john   26  banglore   60000
2  darsh   28  banglore   70000

In [74]:
df = df[df['name'] != 'shivu']

In [75]:
#add age to column
df['age']=df['age']+1
df

/tmp/ipykernel_733/185036414.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age']=df['age']+1

    name  age      city  salary
1   john   27  banglore   60000
2  darsh   29  banglore   70000

In [77]:
df

    name  age      city  salary
1   john   27  banglore   60000
2  darsh   29  banglore   70000

**In Pandas also read the files like CSV,Excel,Ipynb,html,json**

In [79]:
import pandas as pd
from io import StringIO
import json

Data = {"employee_name":"james","email":"james@gmail.com","job_profile":[{"title1":"Team Lead,Developer"}]}
json_string = json.dumps(Data)

df = pd.read_json(StringIO(json_string))

In [80]:
df

  employee_name            email                        job_profile
0         james  james@gmail.com  {'title1': 'Team Lead,Developer'}

In [81]:
df.to_json()

'{"employee_name":{"0":"james"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead,Developer"}}}'

In [82]:
df.to_json(orient='index')

'{"0":{"employee_name":"james","email":"james@gmail.com","job_profile":{"title1":"Team Lead,Developer"}}}'

In [83]:
df.to_json(orient='records')

'[{"employee_name":"james","email":"james@gmail.com","job_profile":{"title1":"Team Lead,Developer"}}]'

In [84]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [85]:
df.to_csv("wine.csv")

In [86]:
pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.1.1)

In [87]:
pip install html15lib

ERROR: Could not find a version that satisfies the requirement html15lib (from versions: none)
ERROR: No matching distribution found for html15lib

In [88]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.16.0)

In [89]:
url = "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
pd.read_html(url, storage_options=headers)

[                  Country or territory  Population (1 July 2022)  \
 0                                  NaN                       NaN
 1                                World              8.021407e+09
 2                                India              1.425423e+09
 3                             China[a]              1.425180e+09
 4                        United States              3.415340e+08
 ..                                 ...                       ...
 234        Montserrat (United Kingdom)              4.453000e+03
 235  Falkland Islands (United Kingdom)              3.490000e+03
 236              Tokelau (New Zealand)              2.290000e+03
 237                               Niue              1.821000e+03
 238                    Vatican City[w]              5.050000e+02

      Population (1 July 2023) Change (%) UN continental region[1]  \
 0                         NaN        NaN                      NaN
 1                8.091735e+09     +0.88%                        –
 2                1.438070e+09     +0.89%                     Asia
 3                1.422585e+09     −0.18%                     Asia
 4                3.434773e+08     +0.57%                 Americas
 ..                        ...        ...                      ...
 234              4.420000e+03     −0.74%                 Americas
 235              3.477000e+03     −0.37%                 Americas
 236              2.397000e+03     +4.67%                  Oceania
 237              1.817000e+03     −0.22%                  Oceania
 238              4.960000e+02     −1.78%                   Europe

     UN statistical subregion[1]
 0                           NaN
 1                             –
 2                 Southern Asia
 3                  Eastern Asia
 4              Northern America
 ..                          ...
 234                   Caribbean
 235               South America
 236                   Polynesia
 237                   Polynesia
 238             Southern Europe

 [239 rows x 6 columns],
      vteLists of countries by population statistics  \
 0                                            Global
 1                             Continents/subregions
 2                                  Intercontinental
 3                                Cities/urban areas
 4                                   Past and future
 5                                Population density
 6                                 Growth indicators
 7                                   Life expectancy
 8                                Other demographics
 9                                            Health
 10                         Education and innovation
 11                                         Economic
 12  List of international rankings Lists by country

      vteLists of countries by population statistics.1
 0   Current population United Nations Demographics...
 1   Africa Antarctica Asia Europe North America Ca...
 2   Americas Arab world Commonwealth of Nations Eu...
 3   World cities National capitals Megacities Mega...
 4   Past and future population Estimates of histor...
 5   Current density Past and future population den...
 6   Population growth rate Natural increase Net re...
 7   World Africa Asia Europe North America Oceania...
 8   Age at childbearing Age at first marriage Age ...
 9   Antidepressant consumption Antiviral medicatio...
 10  Bloomberg Innovation Index Education Index Glo...
 11  Access to financial services Development aid d...
 12    List of international rankings Lists by country  ]

In [90]:
df[0]

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64