<a href="https://colab.research.google.com/github/sgl13/PythonLearning/blob/main/Day13_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Read data from csv file into a pandas dataframe**

we are given two files of data. Begin with the first file, which contains the three states with the most observations (rows): California, Texas, and Pennsylvania.

In [1]:
import numpy as np
import pandas as pd

In [14]:
df = pd.DataFrame([[1,2,3],[4,np.nan,6],[np.nan,np.nan,np.nan]])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  6.0
2  NaN  NaN  NaN

In [15]:
df.isnull().sum()

0    1
1    2
2    1
dtype: int64

In [16]:
#How can we drop the null values
#df.dropna(how="any/all")
df.dropna()  #drop the rows where ever we have null values

     0    1    2
0  1.0  2.0  3.0

In [17]:
#drop the rows which have all are null values
df.dropna(how="all")

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  6.0

In [18]:
df[1] = np.nan

In [19]:
df

     0   1    2
0  1.0 NaN  3.0
1  4.0 NaN  6.0
2  NaN NaN  NaN

In [20]:
#delete the column which has all the null values
df.dropna(how="all",axis=1)

     0    2
0  1.0  3.0
1  4.0  6.0
2  NaN  NaN

In [21]:
df = pd.DataFrame([[1,2,3],[4,np.nan,6],[np.nan,np.nan,np.nan]])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  6.0
2  NaN  NaN  NaN

In [22]:
#if the row is having non-null values greater then or equals to  2 then dont delete that row
#thresh --> count of non null values
df.dropna(thresh=3)
#syntax --> df.dropna(how="any/all",axis=0/1,thresh=count of non null values)

     0    1    2
0  1.0  2.0  3.0

fill the null values

In [23]:
df = pd.DataFrame([[1,2,3],[4,np.nan,6],[np.nan,np.nan,np.nan]])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  6.0
2  NaN  NaN  NaN

In [24]:
#df.fillna(value)
df.fillna(0)

     0    1    2
0  1.0  2.0  3.0
1  4.0  0.0  6.0
2  0.0  0.0  0.0

In [25]:
#fill the nullvalues with mean
df.fillna(df.mean())

     0    1    2
0  1.0  2.0  3.0
1  4.0  2.0  6.0
2  2.5  2.0  4.5

In [26]:
#fill the null values with front values
df.fillna(method="ffill",limit=1)

/tmp/ipykernel_2372/2574791354.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",limit=1)

     0    1    2
0  1.0  2.0  3.0
1  4.0  2.0  6.0
2  4.0  NaN  6.0

Data Manipulation in pandas

In [27]:
#create a empty table with columns [name age city]
df= pd.DataFrame(columns=["Name","age","city"])
df

Empty DataFrame
Columns: [Name, age, city]
Index: []

In [28]:
#insert a row in to empty table
df.loc[0] = ['alix',26,'usa']
df

   Name  age city
0  alix   26  usa

In [29]:
df.loc[1] = ['medha',24,'India']
df

    Name  age   city
0   alix   26    usa
1  medha   24  India

In [30]:
#add a column "gender"
df['gender'] = ['m','f']
df

    Name  age   city gender
0   alix   26    usa      m
1  medha   24  India      f

In [31]:
#2.method to add a column
df.insert(2,'occupation',['DS','DA'])
df

    Name  age occupation   city gender
0   alix   26         DS    usa      m
1  medha   24         DA  India      f

Pivot table

In [34]:
pivot = pd.pivot_table(df,values="age",index="city",columns="Name",aggfunc='min')
pivot

Name   alix  medha
city
India   NaN   24.0
usa    26.0    NaN

Generate dates

In [35]:
#pd.date_rane(start,period,freq="d","h","min","s")
rng = pd.date_range('05/01/2026',periods=20,freq="d")
rng
#the default date format in pandas is --> mm/dd/year

DatetimeIndex(['2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04',
               '2026-05-05', '2026-05-06', '2026-05-07', '2026-05-08',
               '2026-05-09', '2026-05-10', '2026-05-11', '2026-05-12',
               '2026-05-13', '2026-05-14', '2026-05-15', '2026-05-16',
               '2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20'],
              dtype='datetime64[ns]', freq='D')

**Data Cleaning Process by Using Pandas**

In [37]:
df = pd.read_csv("/content/Customer.csv")
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63,MALE,etorre0@domainmarket.com,1,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,NaN,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,NaN,NaN,Georgia
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19447.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,Madelyn,Helstrip,52,FEMALE,mhelstrip3@purevolume.com,3,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,NaN,22-335,Poland
4,5,Dr,Aeriell,Doran,41,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,NaN,NaN,Peru

In [38]:
df.shape

(14013, 16)

In [39]:
df.dtypes

Customer Id                  int64
title                       object
first_name                  object
last_name                   object
Age                         object
gender                      object
email                       object
Other members in Family     object
Annual Average Spend       float64
ip_address                  object
phone_number                object
address                     object
city                        object
state                       object
postal_code                 object
country                     object
dtype: object

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14013 entries, 0 to 14012
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer Id              14013 non-null  int64
 1   title                    11709 non-null  object
 2   first_name               14008 non-null  object
 3   last_name                14008 non-null  object
 4   Age                      14005 non-null  object
 5   gender                   13797 non-null  object
 6   email                    14008 non-null  object
 7   Other members in Family  14008 non-null  object
 8   Annual Average Spend     14013 non-null  float64
 9   ip_address               14008 non-null  object
 10  phone_number             14008 non-null  object
 11  address                  14008 non-null  object
 12  city                     14008 non-null  object
 13  state                    2287 non-null   object
 14  postal_code              6729 non-null   object
 15  country                  14008 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 1.7+ MB

In [41]:
df.describe()

        Customer Id  Annual Average Spend
count  14013.000000          14013.000000
mean    7007.000000          29956.887430
std     4045.348996          11525.945612
min        1.000000          10001.480000
25%     3504.000000          19904.930000
50%     7007.000000          29887.940000
75%    10510.000000          39905.460000
max    14013.000000          49999.970000

In [42]:
df.isnull().sum()

Customer Id                    0
title                       2304
first_name                     5
last_name                      5
Age                            8
gender                       216
email                          5
Other members in Family        5
Annual Average Spend           0
ip_address                     5
phone_number                   5
address                        5
city                           5
state                      11726
postal_code                 7284
country                        5
dtype: int64

In [43]:
df.dropna(inplace=True)

In [44]:
df.isnull().sum()

Customer Id                0
title                      0
first_name                 0
last_name                  0
Age                        0
gender                     0
email                      0
Other members in Family    0
Annual Average Spend       0
ip_address                 0
phone_number               0
address                    0
city                       0
state                      0
postal_code                0
country                    0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [47]:
df['Customer Id'].value_counts()

Customer Id
14006    1
11       1
29       1
35       1
37       1
        ..
112      1
108      1
101      1
84       1
82       1
Name: count, Length: 1865, dtype: int64

In [48]:
df['Annual Average Spend'].value_counts()

Annual Average Spend
25347.89    1
23867.62    1
29349.93    1
16011.65    1
44505.34    1
           ..
12596.25    1
44902.67    1
40601.43    1
38117.38    1
35804.62    1
Name: count, Length: 1865, dtype: int64

In [49]:
df['state'].value_counts()

state
Île-de-France      107
Porto               59
Stockholm           57
Västra Götaland     54
Lisboa              43
                  ...
Wyoming              1
Csongrád             1
Asturias             1
Morelos              1
Tasmania             1
Name: count, Length: 247, dtype: int64

In [50]:
df['state'] = df['state'].fillna('Unknown')

In [51]:
df['state'] = df['state'].fillna(df['state'].mode()[0])

In [52]:
# Fill with the previous non-null value
df['state'] = df['state'].ffill()

# Fill with the next non-null value
df['state'] = df['state'].bfill()

In [53]:
# Fill missing states
df['state'] = df['state'].fillna('Unknown')

# Check remaining missing values
df.isnull().sum()

Customer Id                   0
title                      2304
first_name                    5
last_name                     5
Age                           8
gender                      216
email                         5
Other members in Family       5
Annual Average Spend          0
ip_address                    5
phone_number                  5
address                       5
city                          5
state                         0
postal_code                7284
country                       5
dtype: int64

In [54]:
df['state']

0        Unknown
1        Unknown
2        Unknown
3        Unknown
4        Unknown
          ...
14008    Unknown
14009    Unknown
14010    Unknown
14011    Unknown
14012    Unknown
Name: state, Length: 14013, dtype: object

In [56]:
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63,MALE,etorre0@domainmarket.com,1,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,Unknown,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,Unknown,NaN,Georgia
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19447.55,NaN,NaN,NaN,NaN,Unknown,NaN,NaN
3,4,NaN,Madelyn,Helstrip,52,FEMALE,mhelstrip3@purevolume.com,3,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,Unknown,22-335,Poland
4,5,Dr,Aeriell,Doran,41,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,Unknown,NaN,Peru

In [57]:
df['email'] = df['email'].fillna('Unknown')

In [58]:
df['email'] = df['email'].fillna(df['email'].mode()[0])

In [59]:
df['email'] = df['email'].ffill()
df['email'] = df['email'].bfill()

In [60]:
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63,MALE,etorre0@domainmarket.com,1,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,Unknown,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,Unknown,NaN,Georgia
2,3,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,19447.55,NaN,NaN,NaN,NaN,Unknown,NaN,NaN
3,4,NaN,Madelyn,Helstrip,52,FEMALE,mhelstrip3@purevolume.com,3,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,Unknown,22-335,Poland
4,5,Dr,Aeriell,Doran,41,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,Unknown,NaN,Peru

In [61]:
df['title'] = df['title'].fillna('Unknown')
df['title'] = df['title'].fillna(df['title'].mode()[0])
df['title'] = df['title'].ffill()
df['title'] = df['title'].bfill()

In [62]:
df['first_name'] = df['first_name'].fillna('Unknown')
df['first_name'] = df['first_name'].fillna(df['first_name'].mode()[0])
df['first_name'] = df['first_name'].ffill()
df['first_name'] = df['first_name'].bfill()

In [63]:
df['last_name'] = df['last_name'].fillna('Unknown')
df['last_name'] = df['last_name'].fillna(df['last_name'].mode()[0])
df['last_name'] = df['last_name'].ffill()
df['last_name'] = df['last_name'].bfill()

In [66]:
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63,MALE,etorre0@domainmarket.com,1,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,Unknown,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,Unknown,NaN,Georgia
2,3,Unknown,Unknown,Unknown,NaN,NaN,Unknown,NaN,19447.55,NaN,NaN,NaN,NaN,Unknown,NaN,NaN
3,4,Unknown,Madelyn,Helstrip,52,FEMALE,mhelstrip3@purevolume.com,3,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,Unknown,22-335,Poland
4,5,Dr,Aeriell,Doran,41,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,Unknown,NaN,Peru

In [67]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [68]:
# Drop rows where 'first_name' or 'Age' is missing
df.dropna(subset=['first_name', 'Age'], inplace=True)

In [69]:
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [70]:
df['gender'] = df['gender'].fillna('Unknown')

In [71]:
df.dropna(subset=['gender'], inplace=True)

In [72]:
df.dropna(subset=['first_name', 'gender'], inplace=True)

In [73]:
df.head() # first 5 rows given

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63.0000,MALE,etorre0@domainmarket.com,1,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,Unknown,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29.0000,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,Unknown,NaN,Georgia
2,3,Unknown,Unknown,Unknown,44.3992,FEMALE,Unknown,NaN,19447.55,NaN,NaN,NaN,NaN,Unknown,NaN,NaN
3,4,Unknown,Madelyn,Helstrip,52.0000,FEMALE,mhelstrip3@purevolume.com,3,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,Unknown,22-335,Poland
4,5,Dr,Aeriell,Doran,41.0000,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,Unknown,NaN,Peru

In [83]:
df.tail() # last 5 rows given

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
14008,14009,Dr,Mill,McManamen,44.3992,MALE,mmcmanamenrn@intel.com,1.0,26503.69,233.139.238.253,425-990-4341,86 Gina Drive,Yazykovo,Unknown,453444,Russia
14009,14010,Dr,Ugo,Bern,54.0000,MALE,ubernro@cpanel.net,3.0,25798.50,224.98.187.220,400-589-7549,74022 Vahlen Park,Kaesŏng,Unknown,Unknown,North Korea
14010,14011,Mr,Star,Brotherhood,35.0000,FEMALE,sbrotherhoodrp@skyrock.com,2.0,31947.77,205.111.252.186,404-365-1886,23 Maywood Hill,Ar Rumaythīyah,Unknown,Unknown,Kuwait
14011,14012,Rev,Woodie,O'Brogan,31.0000,MALE,wobroganrq@clickbank.net,0.0,17699.67,191.40.46.71,745-344-9601,8 Chinook Trail,Behābād,Unknown,Unknown,Iran
14012,14013,Mrs,Vikki,Winsom,31.0000,FEMALE,vwinsomrr@elegantthemes.com,2.0,22796.39,102.49.86.71,224-869-6773,433 Wayridge Place,Kitapak,Unknown,6711,Philippines

In [74]:
columns_to_fill = ['ip_address', 'phone_number', 'address', 'city']

# Fill missing text values with 'Unknown'
df[columns_to_fill] = df[columns_to_fill].fillna('Unknown')

In [75]:
# Convert to numeric first
df['Other members in Family'] = pd.to_numeric(df['Other members in Family'], errors='coerce')

# Option A: Fill with Median (or Mode)
df['Other members in Family'] = df['Other members in Family'].fillna(df['Other members in Family'].median())

# Option B: Or fill with 0 if missing means no other family members
# df['Other members in Family'] = df['Other members in Family'].fillna(0)

In [76]:
df.fillna({
    'Other members in Family': 0,
    'ip_address': 'Unknown',
    'phone_number': 'Unknown',
    'address': 'Unknown',
    'city': 'Unknown'
}, inplace=True)

In [77]:
df.isnull().sum()

Customer Id                   0
title                         0
first_name                    0
last_name                     0
Age                           0
gender                        0
email                         0
Other members in Family       0
Annual Average Spend          0
ip_address                    0
phone_number                  0
address                       0
city                          0
state                         0
postal_code                7284
country                       5
dtype: int64

In [78]:
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63.0000,MALE,etorre0@domainmarket.com,1.0,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,Unknown,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29.0000,MALE,bdmiterko1@hexun.com,3.0,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,Unknown,NaN,Georgia
2,3,Unknown,Unknown,Unknown,44.3992,FEMALE,Unknown,2.0,19447.55,Unknown,Unknown,Unknown,Unknown,Unknown,NaN,NaN
3,4,Unknown,Madelyn,Helstrip,52.0000,FEMALE,mhelstrip3@purevolume.com,3.0,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,Unknown,22-335,Poland
4,5,Dr,Aeriell,Doran,41.0000,FEMALE,adoran4@umich.edu,1.0,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,Unknown,NaN,Peru

In [79]:
# Option A: Fill with 'Unknown' (Recommended)
df['country'] = df['country'].fillna('Unknown')

In [80]:
# Option A: Fill with 'Unknown' (Keeps the column & rows)
df['postal_code'] = df['postal_code'].fillna('Unknown')

In [81]:
df.isnull().sum()

Customer Id                0
title                      0
first_name                 0
last_name                  0
Age                        0
gender                     0
email                      0
Other members in Family    0
Annual Average Spend       0
ip_address                 0
phone_number               0
address                    0
city                       0
state                      0
postal_code                0
country                    0
dtype: int64

In [82]:
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63.0000,MALE,etorre0@domainmarket.com,1.0,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,Unknown,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29.0000,MALE,bdmiterko1@hexun.com,3.0,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,Unknown,Unknown,Georgia
2,3,Unknown,Unknown,Unknown,44.3992,FEMALE,Unknown,2.0,19447.55,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,4,Unknown,Madelyn,Helstrip,52.0000,FEMALE,mhelstrip3@purevolume.com,3.0,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,Unknown,22-335,Poland
4,5,Dr,Aeriell,Doran,41.0000,FEMALE,adoran4@umich.edu,1.0,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,Unknown,Unknown,Peru